server:
  port: 7000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: api-service
          uri: http://api-service:7001/
          predicates:
            - Path=/api/**