spring:
  application:
    name: parsers-manager-service
  kafka:
    bootstrap-servers: http://kafka-server:9092
    producer:
      client-id: parsers-manager-service
    template:
      default-topic: parse-comic-task
    consumer:
      group-id: parsers-manage-service-group-1
      max-poll-records: 2000
  mandatory-file-encoding: UTF-8

  elasticsearch:
    jest:
      proxy:
        host: elasticsearch
        port: 9200
  data:
    mongodb:
      database: picstories
      #port: 27017
      uri: mongodb://picstories:picstories@mongo:27017/picstories?replicaSet=rs0
      #username: picstories
      #password: picstories

logging:
  level:
    org.springframework:
      security: DEBUG
      web: DEBUG

tpd:
  consume-topic: update-comic-task

server:
  port: 7003